/// Tabela auxiliar para organizacao de medidas DAX. Nao contem dados.
table _Medidas
	lineageTag: eb6c79b4-830d-4313-88e3-0dde8cfe8ee6

	/// Contagem total de transacoes de vendas
	measure 'Total Vendas' = COUNTROWS(fVendas)
		formatString: #,##0
		displayFolder: Basicas
		lineageTag: 617f3e8e-c508-461e-899c-da2ec4b897c9

	/// Soma do valor total de todas as vendas
	measure 'Receita Bruta' = SUM(fVendas[ValorTotal])
		formatString: R$ #,##0.00
		displayFolder: Basicas
		lineageTag: c5abd604-9735-4129-8fb9-1195e5ddf0fe

	/// Soma total de unidades vendidas
	measure 'Quantidade Total' = SUM(fVendas[Quantidade])
		formatString: #,##0
		displayFolder: Basicas
		lineageTag: 488c563f-863d-44d3-ab02-816515ba0615

	/// Valor medio por transacao de venda
	measure 'Ticket Medio' = DIVIDE([Receita Bruta], [Total Vendas])
		formatString: R$ #,##0.00
		displayFolder: Basicas
		lineageTag: 6fc89501-8926-465f-9616-92e2d5bda4a8

	/// Media do preco unitario praticado nas vendas
	measure 'Preco Medio Unitario' = AVERAGE(fVendas[PrecoUnitario])
		formatString: R$ #,##0.00
		displayFolder: Basicas
		lineageTag: 5153f904-1560-4bcd-b299-b6efae367bb5

	/// Media de unidades por transacao
	measure 'Quantidade Media por Venda' = AVERAGE(fVendas[Quantidade])
		formatString: #,##0.00
		displayFolder: Basicas
		lineageTag: 8d48c13b-345c-42fd-b483-b2a68a2083cf

	/// Quantidade de clientes distintos com vendas no periodo
	measure 'Total Clientes Ativos' = DISTINCTCOUNT(fVendas[IdCliente])
		formatString: #,##0
		displayFolder: Basicas
		lineageTag: c60450b2-11b9-4422-9650-b006fda08335

	/// Quantidade de produtos distintos vendidos no periodo
	measure 'Total Produtos Vendidos' = DISTINCTCOUNT(fVendas[IdProduto])
		formatString: #,##0
		displayFolder: Basicas
		lineageTag: 907f9f93-b2a3-4546-8722-3049c8a05662

	/// Receita media por cliente ativo
	measure 'Receita por Cliente' = DIVIDE([Receita Bruta], [Total Clientes Ativos])
		formatString: R$ #,##0.00
		displayFolder: Basicas
		lineageTag: 9012942f-8a74-44f8-ab33-e90297d2b34b

	/// Custo total baseado no custo unitario do produto x quantidade
	measure 'Custo Total' = SUMX(fVendas, RELATED(dProdutos[CustoUnitario]) * fVendas[Quantidade])
		formatString: R$ #,##0.00
		displayFolder: Lucratividade
		lineageTag: 49004631-f0c5-454e-a7c4-6a88c45a4897

	/// Diferenca entre receita bruta e custo total
	measure 'Lucro Bruto' = [Receita Bruta] - [Custo Total]
		formatString: R$ #,##0.00
		displayFolder: Lucratividade
		lineageTag: 253bee48-932a-4afb-9b76-a8c1a5717778

	/// Percentual de margem bruta sobre a receita
	measure 'Margem Bruta %' = DIVIDE([Lucro Bruto], [Receita Bruta])
		formatString: 0.00%
		displayFolder: Lucratividade
		lineageTag: a010d43b-54d8-42ae-9368-a843b4145d4b

	/// Percentual de markup medio (receita sobre custo)
	measure 'Markup Medio %' = VAR __ReceitaTotal = [Receita Bruta] VAR __CustoTotal = [Custo Total] RETURN DIVIDE(__ReceitaTotal - __CustoTotal, __CustoTotal)
		formatString: 0.00%
		displayFolder: Lucratividade
		lineageTag: ec5b24f6-da49-4c8e-9e91-8f63b261b94b

	/// Total de vendas com status Concluida
	measure 'Vendas Concluidas' = CALCULATE([Total Vendas], fVendas[Status] = "Concluída")
		formatString: #,##0
		displayFolder: Status
		lineageTag: 6bbba5df-65cd-46c0-a044-744a25d3740c

	/// Total de vendas com status Cancelada
	measure 'Vendas Canceladas' = CALCULATE([Total Vendas], fVendas[Status] = "Cancelada")
		formatString: #,##0
		displayFolder: Status
		lineageTag: 4b09f894-6939-4b9e-90ed-6f3d65e16bef

	/// Total de vendas com status Pendente
	measure 'Vendas Pendentes' = CALCULATE([Total Vendas], fVendas[Status] = "Pendente")
		formatString: #,##0
		displayFolder: Status
		lineageTag: 5b427b8f-453d-4ddd-96db-6e71d8b6198e

	/// Total de vendas com status Devolvida
	measure 'Vendas Devolvidas' = CALCULATE([Total Vendas], fVendas[Status] = "Devolvida")
		formatString: #,##0
		displayFolder: Status
		lineageTag: d5a99648-174f-437e-b52a-944e0c8af042

	/// Percentual de vendas canceladas sobre o total
	measure 'Taxa Cancelamento %' = DIVIDE([Vendas Canceladas], [Total Vendas])
		formatString: 0.00%
		displayFolder: Status
		lineageTag: 3a6334d1-5e7c-4d23-826e-8a2aac7e9a90

	/// Percentual de vendas devolvidas sobre o total
	measure 'Taxa Devolucao %' = DIVIDE([Vendas Devolvidas], [Total Vendas])
		formatString: 0.00%
		displayFolder: Status
		lineageTag: f3547ef4-b701-4faf-bc14-109f40a95f82

	/// Receita somente das vendas concluidas (sem canceladas/devolvidas)
	measure 'Receita Liquida' = CALCULATE([Receita Bruta], fVendas[Status] = "Concluída")
		formatString: R$ #,##0.00
		displayFolder: Status
		lineageTag: 2a9351d6-6d62-425a-b5e3-3d119b3ff78a

	/// Receita via PIX
	measure 'Receita PIX' = CALCULATE([Receita Bruta], fVendas[FormaPagamento] = "PIX")
		formatString: R$ #,##0.00
		displayFolder: Pagamento
		lineageTag: 82a06200-4ad9-4376-ade0-c65c89803728

	/// Receita via Cartao Credito
	measure 'Receita Cartao Credito' = CALCULATE([Receita Bruta], fVendas[FormaPagamento] = "Cartão Crédito")
		formatString: R$ #,##0.00
		displayFolder: Pagamento
		lineageTag: 8d772af4-2c86-4072-8ba6-7116f5a5a147

	/// Receita via Boleto
	measure 'Receita Boleto' = CALCULATE([Receita Bruta], fVendas[FormaPagamento] = "Boleto")
		formatString: R$ #,##0.00
		displayFolder: Pagamento
		lineageTag: a5170b53-e32b-45a8-9809-00292673a65a

	/// Percentual da forma de pagamento dominante no contexto
	measure '% Forma Pagamento' = VAR __Total = CALCULATE([Total Vendas], ALL(fVendas[FormaPagamento])) RETURN DIVIDE([Total Vendas], __Total)
		formatString: 0.00%
		displayFolder: Pagamento
		lineageTag: b08b9fe5-5769-46f7-9aa2-6ce1cd0808c3

	/// Receita bruta do mesmo periodo no ano anterior (SAMEPERIODLASTYEAR)
	measure 'Receita Ano Anterior' = CALCULATE([Receita Bruta], SAMEPERIODLASTYEAR(dCalendario[DataCompleta]))
		formatString: R$ #,##0.00
		displayFolder: Time Intelligence
		lineageTag: cf1508de-b5fa-45d2-80bb-02753663a02a

	/// Variacao absoluta da receita vs ano anterior
	measure 'Variacao YoY' = [Receita Bruta] - [Receita Ano Anterior]
		formatString: R$ #,##0.00
		displayFolder: Time Intelligence
		lineageTag: fcbe412b-77a4-4ef9-9823-2088ec5f5604

	/// Crescimento percentual da receita vs ano anterior
	measure 'Crescimento YoY %' = DIVIDE([Variacao YoY], [Receita Ano Anterior])
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: cf4a90ed-ffeb-47bb-8eef-6f713e79a5ec

	/// Receita acumulada do ano ate a data corrente (Year to Date)
	measure 'Receita YTD' = CALCULATE([Receita Bruta], DATESYTD(dCalendario[DataCompleta]))
		formatString: R$ #,##0.00
		displayFolder: Time Intelligence
		lineageTag: 560119fc-7ca1-4623-88d3-e28e440b2878

	/// Receita acumulada no mesmo periodo do ano anterior (YTD ano anterior)
	measure 'Receita YTD Ano Anterior' = CALCULATE([Receita Bruta], DATESYTD(SAMEPERIODLASTYEAR(dCalendario[DataCompleta])))
		formatString: R$ #,##0.00
		displayFolder: Time Intelligence
		lineageTag: 97caed13-32e2-4835-9ffe-470d82a4158c

	/// Variacao percentual do YTD atual vs YTD ano anterior
	measure 'Crescimento YTD %' = DIVIDE([Receita YTD] - [Receita YTD Ano Anterior], [Receita YTD Ano Anterior])
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 180afc41-ce32-427d-97f6-2e2876a2a927

	/// Receita acumulada no mes (Month to Date)
	measure 'Receita MTD' = CALCULATE([Receita Bruta], DATESMTD(dCalendario[DataCompleta]))
		formatString: R$ #,##0.00
		displayFolder: Time Intelligence
		lineageTag: 0b016e97-c923-459e-9d87-cd428d54dce8

	/// Receita acumulada no trimestre (Quarter to Date)
	measure 'Receita QTD' = CALCULATE([Receita Bruta], DATESQTD(dCalendario[DataCompleta]))
		formatString: R$ #,##0.00
		displayFolder: Time Intelligence
		lineageTag: 68aa8962-e6b6-4c28-9ce8-b4b001dc9070

	/// Receita do mes anterior ao periodo selecionado
	measure 'Receita Mes Anterior' = CALCULATE([Receita Bruta], PREVIOUSMONTH(dCalendario[DataCompleta]))
		formatString: R$ #,##0.00
		displayFolder: Time Intelligence
		lineageTag: 96f13581-774d-4e16-a4f3-a793d2799cb4

	/// Crescimento percentual da receita vs mes anterior (MoM)
	measure 'Crescimento MoM %' = VAR __Atual = [Receita Bruta] VAR __Anterior = [Receita Mes Anterior] RETURN DIVIDE(__Atual - __Anterior, __Anterior)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: f3888947-c294-4cf8-96c1-97344718503e

	/// Media movel da receita nos ultimos 3 meses
	measure 'Media Movel 3 Meses' = AVERAGEX(DATESINPERIOD(dCalendario[DataCompleta], MAX(dCalendario[DataCompleta]), -3, MONTH), [Receita Bruta])
		formatString: R$ #,##0.00
		displayFolder: Time Intelligence
		lineageTag: b67bb8ef-06de-4300-82fe-6fc86207418b

	/// Receita acumulada (running total) ao longo do tempo
	measure 'Receita Acumulada' = VAR __MaxData = MAX(dCalendario[DataCompleta]) RETURN CALCULATE([Receita Bruta], dCalendario[DataCompleta] <= __MaxData, ALL(dCalendario))
		formatString: R$ #,##0.00
		displayFolder: Time Intelligence
		lineageTag: e38fbaac-6f2f-4598-ad0e-5bb6f59c39b2

	/// Ranking do produto pela receita bruta (do maior para menor)
	measure 'Rank Produto Receita' = IF(HASONEVALUE(dProdutos[NomeProduto]), RANKX(ALL(dProdutos[NomeProduto]), [Receita Bruta],, DESC, Dense))
		formatString: #,##0
		displayFolder: Ranking
		lineageTag: eb9b1c28-08a8-4fe1-ac0e-1811be298538

	/// Ranking do cliente pela receita bruta
	measure 'Rank Cliente Receita' = IF(HASONEVALUE(dClientes[NomeCliente]), RANKX(ALL(dClientes[NomeCliente]), [Receita Bruta],, DESC, Dense))
		formatString: #,##0
		displayFolder: Ranking
		lineageTag: da462592-8e8e-4a20-8606-2b35ccffd308

	/// Ranking da categoria de produto pela receita bruta
	measure 'Rank Categoria Receita' = IF(HASONEVALUE(dProdutos[Categoria]), RANKX(ALL(dProdutos[Categoria]), [Receita Bruta],, DESC, Dense))
		formatString: #,##0
		displayFolder: Ranking
		lineageTag: a2d3d6e4-0aac-4e4c-845a-ddd40cfa0895

	/// Ranking da regiao pela receita bruta
	measure 'Rank Regiao Receita' = IF(HASONEVALUE(dLocalizacao[Regiao]), RANKX(ALL(dLocalizacao[Regiao]), [Receita Bruta],, DESC, Dense))
		formatString: #,##0
		displayFolder: Ranking
		lineageTag: 22c2f545-ca22-49e4-87df-698816517c92

	/// Ranking do produto pela quantidade vendida
	measure 'Rank Produto Quantidade' = IF(HASONEVALUE(dProdutos[NomeProduto]), RANKX(ALL(dProdutos[NomeProduto]), [Quantidade Total],, DESC, Dense))
		formatString: #,##0
		displayFolder: Ranking
		lineageTag: 0d253556-60df-4fc3-b557-0fcc7c228d52

	/// Ranking do produto pela margem bruta percentual
	measure 'Rank Produto Margem' = IF(HASONEVALUE(dProdutos[NomeProduto]), RANKX(ALL(dProdutos[NomeProduto]), [Margem Bruta %],, DESC, Dense))
		formatString: #,##0
		displayFolder: Ranking
		lineageTag: dd10b17f-a8dc-4351-aebc-5ed60ef1acd6

	/// Ranking do cliente pela quantidade de compras (frequencia)
	measure 'Rank Cliente Frequencia' = IF(HASONEVALUE(dClientes[NomeCliente]), RANKX(ALL(dClientes[NomeCliente]), [Total Vendas],, DESC, Dense))
		formatString: #,##0
		displayFolder: Ranking
		lineageTag: a8542ace-a195-4903-be87-890887f62503

	/// Ranking da cidade pela receita bruta
	measure 'Rank Cidade Receita' = IF(HASONEVALUE(dLocalizacao[Cidade]), RANKX(ALL(dLocalizacao[Cidade]), [Receita Bruta],, DESC, Dense))
		formatString: #,##0
		displayFolder: Ranking
		lineageTag: 10f48de8-5b88-47ad-ba6b-af9e23fab3fa

	/// Ranking do segmento de clientes pela receita bruta
	measure 'Rank Segmento Receita' = IF(HASONEVALUE(dClientes[Segmento]), RANKX(ALL(dClientes[Segmento]), [Receita Bruta],, DESC, Dense))
		formatString: #,##0
		displayFolder: Ranking
		lineageTag: bd5b0b10-6bfa-4de1-898c-4314ff6ac5f9

	/// Percentual da receita do produto vs total geral
	measure '% Participacao Produto' = DIVIDE([Receita Bruta], CALCULATE([Receita Bruta], ALL(dProdutos)))
		formatString: 0.00%
		displayFolder: Participacao
		lineageTag: ce3cadc8-d515-4d6a-a855-4d668670a938

	/// Percentual da receita da regiao vs total geral
	measure '% Participacao Regiao' = DIVIDE([Receita Bruta], CALCULATE([Receita Bruta], ALL(dLocalizacao)))
		formatString: 0.00%
		displayFolder: Participacao
		lineageTag: 5935f816-d482-4fb8-af77-ce7fd15f2d6f

	/// Percentual da receita do segmento vs total geral
	measure '% Participacao Segmento' = DIVIDE([Receita Bruta], CALCULATE([Receita Bruta], ALL(dClientes[Segmento])))
		formatString: 0.00%
		displayFolder: Participacao
		lineageTag: e010a593-e63b-4828-8d61-7e8468389f92

	/// Percentual da receita da categoria vs total geral
	measure '% Participacao Categoria' = DIVIDE([Receita Bruta], CALCULATE([Receita Bruta], ALL(dProdutos[Categoria])))
		formatString: 0.00%
		displayFolder: Participacao
		lineageTag: e5c1f09e-1fe1-4040-b326-c06e614ac8ed

	/// Maior valor de venda individual no periodo filtrado
	measure 'Maior Venda' = MAX(fVendas[ValorTotal])
		formatString: R$ #,##0.00
		displayFolder: Estatisticas
		lineageTag: 518d8b5d-0129-4c80-b148-56f2af795934

	column Medida
		isHidden
		lineageTag: 33366299-f9aa-45fe-9037-2195712b3656
		isNameInferred
		sourceColumn: [Medida]

	partition _Medidas = calculated
		mode: import
		source = ROW("Medida", 0)

