/// Tabela fato com registros de vendas. Granularidade: 1 linha por venda.
table fVendas
	lineageTag: 07ed16ec-dd80-436b-bbcc-367596930282

	/// Chave primaria da tabela Vendas
	column IdVenda
		dataType: string
		lineageTag: 45d77b65-c4f5-4a10-85d8-f8f5dbed4847
		summarizeBy: none
		sourceColumn: ID_Venda

		annotation SummarizationSetBy = Automatic

	/// Data da transacao de venda (FK para dCalendario)
	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: adff9c42-9cdb-4666-acdc-db6e29dec469
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// FK para tabela Clientes
	column IdCliente
		dataType: string
		isHidden
		lineageTag: d0537b52-7f4e-4ad0-a67e-7200eab742e6
		summarizeBy: none
		sourceColumn: ID_Cliente

		annotation SummarizationSetBy = Automatic

	/// FK para tabela Produtos
	column IdProduto
		dataType: string
		isHidden
		lineageTag: 5665e53f-7b11-4346-b4e5-3389e34e9ce1
		summarizeBy: none
		sourceColumn: ID_Produto

		annotation SummarizationSetBy = Automatic

	/// Quantidade vendida
	column Quantidade
		dataType: int64
		formatString: 0
		lineageTag: 19524d5c-3dff-45fd-8782-50c261cfd724
		summarizeBy: sum
		sourceColumn: Quantidade

		annotation SummarizationSetBy = Automatic

	/// Preco unitario do produto na venda
	column PrecoUnitario
		dataType: double
		lineageTag: 2c9f7512-4b02-4717-99d2-701555215d2d
		summarizeBy: none
		sourceColumn: Preço_Unitário

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Valor total da venda (Quantidade x Preco)
	column ValorTotal
		dataType: double
		lineageTag: f03e3073-3b4d-4ab3-8a65-0342c28312ed
		summarizeBy: sum
		sourceColumn: Valor_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Forma de pagamento utilizada (ex: Pix, Cartao, Boleto)
	column FormaPagamento
		dataType: string
		lineageTag: 406d49f8-9c5f-4130-a36d-a212932efc41
		summarizeBy: none
		sourceColumn: Forma_Pagamento

		annotation SummarizationSetBy = Automatic

	/// Status da venda (ex: Concluida, Cancelada, Pendente)
	column Status
		dataType: string
		lineageTag: 0a7ab2a4-f83c-4961-9167-b50e4c1dc479
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition Vendas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\gerso\OneDrive - Minhas Planilhas\Minhas Planilhas\Comunidade Dashmaker\Cursos\Workshop Power BI na era da IA Generativa\Material Workshop\Banco de Dados\Vendas Exemplo.xlsx"), null, true),
				    Vendas_Sheet = Fonte{[Item="Vendas",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Vendas_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID_Venda", type text}, {"Data", type date}, {"ID_Cliente", type text}, {"ID_Produto", type text}, {"Quantidade", Int64.Type}, {"Preço_Unitário", type number}, {"Valor_Total", type number}, {"Forma_Pagamento", type text}, {"Status", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

